Repository drewclem/protege, pull requests merged in 2021-04, with the labels that each got.

#263 Improve the dbseed.js script
  .env.local.template
  dbseed.js
  package.json
  yarn.lock
Labels: developer experience

#266 Added eslint back to the project
  .eslintrc.js
  cypress/.eslintrc.js
  cypress/integration/home.spec.js
  cypress/plugins/index.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: frontend infrastructure

#271 Bug/improve data flow
  components/user/ProfileMenu.js
  layouts/AccountInteriorLayout.js
  pages/candidate/[displayName]/edit-profile.js
  pages/company/[displayName]/edit-profile.js
  pages/sign-up.js
  store/AuthContext.js
Labels: WIP, bug, protege-team
